// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tavhwmpxwwdimzalkdov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhdmh3bXB4d3dkaW16YWxrZG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMzQ3MTksImV4cCI6MjA3MDcxMDcxOX0.-mgEO9Ly8QeOIvnaKDXrnUksYUH-le8kIVjNjhCpj2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});